// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Standardize
{
    internal sealed partial class Vsix
    {
        public const string Id = "Standardize.0b03d9f8-49bb-42f5-a23b-3fa93fe57ca0";
        public const string Name = "Standardize";
        public const string Description = @"Be standard with Standardize.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Noam Levy and Itay Bernstein";
        public const string Tags = "";
    }
}
