// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Standardize
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string StandardizeString = "bf1d201b-3314-4268-a6c6-85eb2e9366ea";
        public static Guid Standardize = new Guid(StandardizeString);

        public const string ImageCatalogGuidString = "-invalid-";
        public static Guid ImageCatalogGuid = new Guid(ImageCatalogGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int VariablesCommand = 0x0101;
        public const int CommentsCommand = 0x0102;
    }
}